### ISSUE TITLE
When installing fonts, the install button says "Install Failed" and then says "Installed"

### ISSUE THREAD

**Issue by ClarkNarvas** [elementary/fonts#15]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
When you click "Install", the button then says "Install Failed" while it's installing and then it says "Installed"

### To Reproduce
1. Click on a font file
2. Click install
3. See error

### Expected behavior
Either something saying "Installing" or something to identify it's installing

### Screenshots or screen recordings
https://www.youtube.com/watch?v=SB5PC_1IxDA

## Platform Information
https://postimg.cc/QFfF4bXN

- [ ] I'm using the latest version from git that I've manually compiled
- [X] I'm using the latest released stable version

**Comment by danirabbit** [comment]
Hey thanks for your report! This repository is for the collection of default fonts shipped with elementary OS. It is not for the GNOME Fonts app shipped by default.

To report an issue with GNOME Fonts, please see their Gitlab page here: https://gitlab.gnome.org/GNOME/gnome-font-viewer
