### ISSUE TITLE
Add noto-color-emoji

### ISSUE THREAD

**Issue by danirabbit** [elementary/fonts#4]
Now that we have color emoji support, we need a color emoji font

**Comment by danirabbit** [comment]
Closing because it's already packaged by Ubuntu so this is more of a `seeds-metapackages` thing

**Comment by codygarver** [comment]
Closed by f6b71b8

**Comment by waldyrious** [comment]
Hey @codygarver, that comment looks like it was meant for a different issue -- or am I missing something?

**Comment by codygarver** [comment]
@waldyrious it was meant for this comment because the fix was applied to this fonts repo, this issue was closed prematurely before.

**Comment by waldyrious** [comment]
Thanks for confirming. I was just making sure, because that commit makes no reference to the Noto font (or noto-color-emoji), only to Raleway.

**Comment by codygarver** [comment]
Sorry, you're correct. Somehow I copied the wrong commit hash. The actual commit is f6b71b8.
