### ISSUE TITLE
Expand elementaryOS's typefaces catalogue

### ISSUE THREAD

**Issue by apcamargo** [elementary/fonts#8]
In the last few years, a huge amount of high-quality free and open source typefaces were published, but elementaryOS stayed stagnant in this area. Thus, I've prepared this proposal of possible typefaces that could be included in elementaryOS to improve it's somewhat poor font catalogue.
I've created separate categories for each kind of typeface to organize the document. Font license information is included.

https://docs.google.com/document/d/1hElei0xMQKLaiL-MKvbUP-huYqQL0uORPy6QYmu4Sw4/

I'm open to add the devs as editors of the document.

**Comment by waldyrious** [comment]
I see you've included Linux Libertine there, which I had suggested in #1. Considering that its latest release was five years ago, perhaps it would be better to use the [Libertinus](https://github.com/libertinus-fonts/libertinus) fork instead, which has remained [fairly active](https://github.com/libertinus-fonts/libertinus/graphs/contributors), including fixing of several long-standing bugs in Linux Libertine.

**Comment by apcamargo** [comment]
Added three new fonts today:
- Microsoft's [Cascadia Code](https://github.com/microsoft/cascadia-code)
- JetBrain's [JetBrain Mono](https://github.com/JetBrains/JetBrainsMono)
- indestructible type*'s [Bodoni*](https://github.com/indestructible-type/Bodoni)

**Comment by meisenzahl** [comment]
Also see https://github.com/elementary/default-settings/issues/199

**Comment by dar5hak** [comment]
Excellent collection! A couple of suggestions for substitution:

- [FiraGO](https://bboxtype.com/typefaces/FiraGO/#!layout=specimen) over Fira Sans for its vaster character coverage
- [Crimson Pro](https://fonts.google.com/specimen/Crimson+Pro) over Crimson Text for its improved readability

**Comment by apcamargo** [comment]
Thanks @dar5hak! Just updated the list.
