### ISSUE TITLE
Consider changing the default monospaced font to Noto Sans Mono

### ISSUE THREAD

**Issue by apcamargo** [elementary/fonts#9]
Noto Sans Mono follows follows the humanistic style and pair much better with elementaryOS's default font (Open Sans) than Roboto Mono. Besides that, it includes a much broader variety of styles (36) than Roboto Mono (10) and covers many more languages.

**Comment by stlee42** [comment]
This will have to be addressed in

[https://github.com/elementary/default-settings/issues/92](https://github.com/elementary/fonts/issues/url)

and not in this repository.

**Comment by stlee42** [comment]
This issue can be closed, please.

**Comment by stlee42** [comment]
what do you think of #19 ?

**Comment by apcamargo** [comment]
Although I personally use Cascadia Mono, I don't think it would fit the rest of the OS typography. Since the change to Inter I think Roboto Mono actually fits better than Noto Sans Mono. Additionaly, I'm not sure if using a font with ligatures by default is a good choice.

**Comment by stlee42** [comment]
Do you think we should close this issue?

**Comment by apcamargo** [comment]
Yep. I'll close it
